# Generated by Django 3.0.5 on 2020-05-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsgiornalistimodel',
            old_name='titolo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='newsgiornalistimodel',
            name='autore',
        ),
        migrations.RemoveField(
            model_name='newsgiornalistimodel',
            name='contenuto',
        ),
        migrations.AlterField(
            model_name='newsarticolimodel',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
