# Generated by Django 3.0.5 on 2020-05-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200520_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticolimodel',
            name='autore',
            field=models.TextField(),
        ),
    ]
