# Generated by Django 3.0.5 on 2020-05-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200520_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticolimodel',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='news.NewsGiornalistiModel'),
        ),
    ]
